version: '3.8'

networks:
 dev:
  driver: bridge

services:
  webapi:
    env_file: .env
    image: metapersona-api:latest
    depends_on:
      - app_db
    container_name: metapersona-api
    volumes:
      - my_keys_volume:/root/.aspnet/DataProtection-Keys
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RPC_URL=${RPC_URL}
      - JKEY=${JKEY}
      - HTTP_PORTS=8080
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=app_db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    networks:
      - dev
    command: >
      bash -c "dotnet ef database update && dotnet run"


  app_db:  
    env_file: .env
    container_name: app_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432" 
    networks:
      - dev

volumes:
  pgdata:
  my_keys_volume:  
