version: '3.8'

services:
  web:
    image: metapersona-web:latest
    container_name: metapersona-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:7000:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
