name: Docker Compose

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: 139786-hel3
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and run Docker Compose
      run: |
        docker build -t metapersona-web:latest .
        docker compose up -d
