name: Docker Compose

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Source .env
      run: |
       cp ~/actions-runner/Env/.env $GITHUB_WORKSPACE/.env
       source .env

    - name: Build and run Docker Compose
      run: |
        docker build -t metapersona-api:latest .
        docker compose up -d
