name: Docker Compose

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Source .env
      run: source ~/actions-runner/Env/.env

    - name: Build and run Docker Compose
      run: |
        # Set up Docker on the self-hosted runner
        sudo service docker start

        # Build Docker image
        docker build -t metapersona-api:latest .

        # Run Docker Compose
        docker-compose up -d
